alias adb-check-device-arch='adb shell getprop ro.product.cpu.abi'
alias adb-read-allprop='adb shell getprop'
alias cp='cp -i'
alias ga='nvim -c "Git" -c "wincmd o"'
alias grep='grep --color=auto'
alias less='less -R'
alias ls='ls --color=auto'
alias mkdir='mkdir -p'
alias ssh-up='eval $(ssh-agent -s)'
alias suspend='systemctl suspend'
alias unlockme='sudo faillock --user $(whoami) --reset'
alias vim='nvim'
